version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      - djangonetwork
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"
    links:
      - db:db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${METHOD}
    command: postgres -N 512
    volumes:
       - db:/data/postgres
    expose:
      - ${POSTGRES_PORT}
    networks:
      - djangonetwork
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"

  test:
    container_name: test
    build:
      context: .
      dockerfile: DockerFile
    command: python manage.py test
    volumes:
      - .:/app
    links:
      - db:db
    depends_on:
      - db

networks:
  djangonetwork:
    driver: bridge

volumes:
    web:
    db:
    test: